### ISSUE TITLE
TSV not correctly parsed

### ISSUE THREAD

**Issue by dejlek** [shenwei356/csvtk#130]
I was trying to analyse Google Books Ngram data, more specifically the 1gram, "S" file from 
http://storage.googleapis.com/books/ngrams/books/datasetsv2.html

```
  dejan@mrak$ csvtk -t nrow googlebooks-eng-all-1gram-20120701-s.gz 
[ERRO] parse error on line 6280251, column 6: bare " in non-quoted-field
```
Looks like TSV is not properly parsed - it is perfectly valid to have one single or double quote in a TSV field...

**Comment by shenwei356** [comment]
add `-l`

**Comment by dejlek** [comment]
Thanks! Perhaps `-t` should assume `-l` as it is completely legal to have quotes like that in TSV file fields.

**Comment by shenwei356** [comment]
Yes, but using `-l` will cause some side effects on output, i.e., adding extra double quotes to fields with a bare quote, e.g.,



```
$ echo -ne "a\tb\tc\"d\n"
a       b       c"d

$ echo -ne "a\tb\tc\"d\n" | csvtk cut -H -t -f 1-
[ERRO] parse error on line 1, column 5: bare " in non-quoted-field

$ echo -ne "a\tb\tc\"d\n" | csvtk cut -H -t -f 1- -l
a       b       "c""d"
```

csvtk uses the CSV parser in the standard library.

**Comment by corneliusroemer** [comment]
Hmm, I also encountered this issue. Maybe there should be a warning that TSV support is limited for csvtk.

Per TSV specs, quotes are ok and should be passed through. The workaround with `-l` is only limited as you show. So there seems to be no 100% workaround and if one wants robust TSV processing one might want to use a different tool as sad as it is.

**Comment by shenwei356** [comment]
Since v0.29.0, it can be handled with `fix-quotes` and `del-quotes`.

Some useful subcommands:

```
  fix             fix CSV/TSV with different numbers of columns in rows
  fix-quotes      fix malformed CSV/TSV caused by double-quotes
  del-quotes      remove extra double quotes added by 'fix-quotes'
```

An example.

```
$ echo -ne "a\tb\tc\"d\n" \
    | csvtk fix-quotes -Ht \
    | csvtk grep -Ht -f 1 -p a \
    | csvtk del-quotes -Ht
a       b       c"d
```

```
$ csvtk -h

  ...
  7. If double-quotes exist in fields not enclosed with double-quotes, e.g.,
         x,a "b" c,1
     It would report error:
         bare " in non-quoted-field.
     Please switch on the flag "-l" or use "csvtk fix-quotes" to fix it.
  8. If somes fields have only a double-quote eighter in the beginning or in the end, e.g.,
         x,d "e","a" b c,1
     It would report error:
         extraneous or missing " in quoted-field
     Please use "csvtk fix-quotes" to fix it, and use "csvtk del-quotes" to reset to the
     original format as needed.
```

**Comment by corneliusroemer** [comment]
Is there a reason not to auto-run the fix-quotes and del-quotes parts when `-t` is on?

For a pipeline, you don't want to add these when you suddenly happen to encounter a `"` months into a project. Things should work with TSV just with the flag `-t` or there should be a more visible warning, in my feeling.

For CLI usage, it's ok if you get an error once in a while, but you don't want that to happen in pipelines.

**Comment by shenwei356** [comment]
csvtk uses CSV/TSV parser from the standard library of Go, which follows FC4180 specifications (https://rfc-editor.org/rfc/rfc4180.html). `fix-quotes` is my patch to make the data compatible with those specifications, while it's not performant and it's hard to be integrated to the API.

**Comment by corneliusroemer** [comment]
I've been of the opinion to discourage use of csvtk with TSV due to this issue.

Now trying to give it a second chance but I have questions :)

For production code, one would have to add the workaround every time, so as to be able to accept all legal TSV input. That's not great. How big is the performance hit? Could you still make the workaround a flag so one doesn't have to run a lot of csvtk commands in tsv mode - commands which are easy to forget?

Also, is your patch 100% waterproof? Does it work with all legal sequences of quotes? Or is it only a limited workaround?

What about the following idea: have tsv files be auto-converted to CSV, then converted back to TSV after normal processing. That means escaping all quotes from TSV -> CSV (and unescaping tabs) and vice versa on the way back.

That would be a non-hacky way to ensure csvtk obeys TSV standards as well.
