### ISSUE TITLE
[ERRO] bufio.Scanner: token too long

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/csvtk#231]
### Prerequisites

- [x ] make sure you're are using the latest version by `csvtk version`
- [ x] read the [usage](http://bioinf.shenwei.me/csvtk/usage/)

### Describe your issue

* [ x] describe the problem
* [ ] provide a reproducible example

Hi, 
I encounter this error when I use the `csvtk space2tab ` command with a very large table. I want to convert a space-delimited file into csv or tsv format, because some of the `csvtk `commands do not correctly handle the space delimiter, even when using ` -d` flag

### Thank you

I'm grateful to users who have greatly helped to report bugs and suggested new features.

I may respond to issues or fix bugs quickly, but I usually implement new features periodically (two or more weeks).

**Comment by shenwei356** [comment]
Oh, it's a common bug, which had been fixed in my other tools.

- [csvtk_windows_amd64.exe.tar.gz](https://github.com/shenwei356/csvtk/files/11905931/csvtk_windows_amd64.exe.tar.gz)
- [csvtk_linux_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/11905930/csvtk_linux_amd64.tar.gz)
- [csvtk_darwin_arm64.tar.gz](https://github.com/shenwei356/csvtk/files/11905929/csvtk_darwin_arm64.tar.gz)
- [csvtk_darwin_amd64.tar.gz](https://github.com/shenwei356/csvtk/files/11905928/csvtk_darwin_amd64.tar.gz)
